// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelChooser():Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetAppStatus():Promise<main.AppStatus>;

export function GetBrowsers():Promise<Array<main.Browser>>;

export function GetChooserData():Promise<main.ChooserRequest>;

export function GetChooserSettings():Promise<main.ChooserSettings>;

export function GetConfig():Promise<main.Config>;

export function GetCurrentURL():Promise<string>;

export function GetProtocolApps():Promise<Array<main.ProtocolApp>>;

export function GetRules():Promise<Array<main.Rule>>;

export function IsChooserMode():Promise<boolean>;

export function IsDevMode():Promise<boolean>;

export function LookupProtocol(arg1:string):Promise<main.ProtocolApp>;

export function OpenDefaultAppsSettings():Promise<void>;

export function OpenWithBrowser(arg1:main.ChooserResponse):Promise<void>;

export function ProcessURL(arg1:string):Promise<string>;

export function RefreshBrowsers():Promise<Array<main.Browser>>;

export function RegisterAsDefaultBrowser():Promise<void>;

export function ReorderRules(arg1:Array<string>):Promise<void>;

export function SaveChooserSettings(arg1:main.ChooserSettings):Promise<void>;

export function SaveRule(arg1:main.Rule):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnregisterAsDefaultBrowser():Promise<void>;

export function ValidateRules():Promise<Array<main.RuleValidation>>;
