// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyDefsUpdate():Promise<string>;

export function ArchiveBrowser(arg1:string):Promise<void>;

export function CancelPicker():Promise<void>;

export function CheckForDefsUpdate():Promise<main.DefsUpdateResult>;

export function DeleteRule(arg1:string):Promise<void>;

export function GetActiveBrowsers():Promise<Array<main.Browser>>;

export function GetAppRedirects():Promise<Array<main.AppRedirect>>;

export function GetAppStatus():Promise<main.AppStatus>;

export function GetBrowsers():Promise<Array<main.Browser>>;

export function GetConfig():Promise<main.Config>;

export function GetCurrentURL():Promise<string>;

export function GetDefsStatus():Promise<main.DefsStatus>;

export function GetPickerData():Promise<main.PickerRequest>;

export function GetPickerSettings():Promise<main.PickerSettings>;

export function GetProtocolApps():Promise<Array<main.ProtocolApp>>;

export function GetRules():Promise<Array<main.Rule>>;

export function IsDevMode():Promise<boolean>;

export function IsFirstRun():Promise<boolean>;

export function IsPickerMode():Promise<boolean>;

export function LookupProtocol(arg1:string):Promise<main.ProtocolApp>;

export function MarkFirstRunComplete():Promise<void>;

export function OpenDefaultAppsSettings():Promise<void>;

export function OpenWithBrowser(arg1:main.PickerResponse):Promise<void>;

export function ProcessURL(arg1:string):Promise<string>;

export function RefreshBrowsers():Promise<Array<main.Browser>>;

export function RegisterAsDefaultBrowser():Promise<void>;

export function ReorderRules(arg1:Array<string>):Promise<void>;

export function ResetDefsToBuiltin():Promise<void>;

export function RevertDefsUpdate():Promise<string>;

export function SavePickerSettings(arg1:main.PickerSettings):Promise<void>;

export function SaveRule(arg1:main.Rule):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetAppRedirectEnabled(arg1:string,arg2:boolean):Promise<void>;

export function UnarchiveBrowser(arg1:string):Promise<void>;

export function UnregisterAsDefaultBrowser():Promise<void>;

export function ValidateRules():Promise<Array<main.RuleValidation>>;
