// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelChooser() {
  return window['go']['main']['App']['CancelChooser']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetBrowsers() {
  return window['go']['main']['App']['GetBrowsers']();
}

export function GetChooserData() {
  return window['go']['main']['App']['GetChooserData']();
}

export function GetChooserSettings() {
  return window['go']['main']['App']['GetChooserSettings']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentURL() {
  return window['go']['main']['App']['GetCurrentURL']();
}

export function GetProtocolApps() {
  return window['go']['main']['App']['GetProtocolApps']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function IsChooserMode() {
  return window['go']['main']['App']['IsChooserMode']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function LookupProtocol(arg1) {
  return window['go']['main']['App']['LookupProtocol'](arg1);
}

export function OpenDefaultAppsSettings() {
  return window['go']['main']['App']['OpenDefaultAppsSettings']();
}

export function OpenWithBrowser(arg1) {
  return window['go']['main']['App']['OpenWithBrowser'](arg1);
}

export function ProcessURL(arg1) {
  return window['go']['main']['App']['ProcessURL'](arg1);
}

export function RefreshBrowsers() {
  return window['go']['main']['App']['RefreshBrowsers']();
}

export function RegisterAsDefaultBrowser() {
  return window['go']['main']['App']['RegisterAsDefaultBrowser']();
}

export function ReorderRules(arg1) {
  return window['go']['main']['App']['ReorderRules'](arg1);
}

export function SaveChooserSettings(arg1) {
  return window['go']['main']['App']['SaveChooserSettings'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function UnregisterAsDefaultBrowser() {
  return window['go']['main']['App']['UnregisterAsDefaultBrowser']();
}

export function ValidateRules() {
  return window['go']['main']['App']['ValidateRules']();
}
