// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPicker() {
  return window['go']['main']['App']['CancelPicker']();
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetBrowsers() {
  return window['go']['main']['App']['GetBrowsers']();
}

export function GetPickerData() {
  return window['go']['main']['App']['GetPickerData']();
}

export function GetPickerSettings() {
  return window['go']['main']['App']['GetPickerSettings']();
}

export function GetClipboardURL() {
  return window['go']['main']['App']['GetClipboardURL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentURL() {
  return window['go']['main']['App']['GetCurrentURL']();
}

export function GetProtocolApps() {
  return window['go']['main']['App']['GetProtocolApps']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetStartWithWindows() {
  return window['go']['main']['App']['GetStartWithWindows']();
}

export function GetTrayData() {
  return window['go']['main']['App']['GetTrayData']();
}

export function IsPickerMode() {
  return window['go']['main']['App']['IsPickerMode']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsTrayMode() {
  return window['go']['main']['App']['IsTrayMode']();
}

export function LaunchBrowserByName(arg1) {
  return window['go']['main']['App']['LaunchBrowserByName'](arg1);
}

export function LookupProtocol(arg1) {
  return window['go']['main']['App']['LookupProtocol'](arg1);
}

export function MarkFirstRunComplete() {
  return window['go']['main']['App']['MarkFirstRunComplete']();
}

export function OpenDefaultAppsSettings() {
  return window['go']['main']['App']['OpenDefaultAppsSettings']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function OpenURLFromClipboard() {
  return window['go']['main']['App']['OpenURLFromClipboard']();
}

export function OpenWithBrowser(arg1) {
  return window['go']['main']['App']['OpenWithBrowser'](arg1);
}

export function ProcessURL(arg1) {
  return window['go']['main']['App']['ProcessURL'](arg1);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshBrowsers() {
  return window['go']['main']['App']['RefreshBrowsers']();
}

export function RegisterAsDefaultBrowser() {
  return window['go']['main']['App']['RegisterAsDefaultBrowser']();
}

export function ReorderRules(arg1) {
  return window['go']['main']['App']['ReorderRules'](arg1);
}

export function SavePickerSettings(arg1) {
  return window['go']['main']['App']['SavePickerSettings'](arg1);
}

export function SaveRule(arg1) {
  return window['go']['main']['App']['SaveRule'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SetStartWithWindows(arg1) {
  return window['go']['main']['App']['SetStartWithWindows'](arg1);
}

export function UnregisterAsDefaultBrowser() {
  return window['go']['main']['App']['UnregisterAsDefaultBrowser']();
}

export function ValidateRules() {
  return window['go']['main']['App']['ValidateRules']();
}
